"""empty message

Revision ID: ceccaec6e120
Revises: 
Create Date: 2022-09-06 12:32:07.608918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceccaec6e120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), server_default='user', nullable=False),
    sa.Column('lastname', sa.String(), server_default='user', nullable=False),
    sa.Column('othername', sa.String(), server_default='', nullable=False),
    sa.Column('phone', sa.String(), server_default='', nullable=False),
    sa.Column('occupation', sa.String(), server_default='', nullable=False),
    sa.Column('income', sa.String(), server_default='', nullable=False),
    sa.Column('address', sa.String(), server_default='', nullable=False),
    sa.Column('state', sa.String(), server_default='', nullable=False),
    sa.Column('dob', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('grant', sa.String(), server_default='', nullable=False),
    sa.Column('credit_score', sa.String(), server_default='', nullable=False),
    sa.Column('grant_reason', sa.String(), server_default='', nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
