"""empty message

Revision ID: 256c4177a6c9
Revises: 8522c6bc8fe9
Create Date: 2022-09-09 17:56:10.005699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256c4177a6c9'
down_revision = '8522c6bc8fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passcode', sa.String(), server_default='', nullable=False))
    op.alter_column('users', 'othername',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'occupation',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'othername',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('users', 'passcode')
    # ### end Alembic commands ###
