"""empty message

Revision ID: 787c18b9f122
Revises: 8a997037c27c
Create Date: 2022-09-06 15:06:05.849652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787c18b9f122'
down_revision = '8a997037c27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
